# Generated by Django 2.0.6 on 2020-08-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IrderItem',
            new_name='OrderItem',
        ),
    ]
